const withCSS = require('@zeit/next-css')
const withFonts = require('next-fonts')
const withImages = require('next-images')
const withSass = require('@zeit/next-sass')
module.exports = withCSS(withFonts(withImages(withSass())))